ALTER TABLE profiles ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS gender TEXT;

CREATE OR REPLACE FUNCTION public.lifemed_ensure_profile_columns()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  ALTER TABLE profiles ADD COLUMN IF NOT EXISTS email TEXT;
  ALTER TABLE profiles ADD COLUMN IF NOT EXISTS phone TEXT;
  ALTER TABLE profiles ADD COLUMN IF NOT EXISTS city TEXT;
  ALTER TABLE profiles ADD COLUMN IF NOT EXISTS gender TEXT;
END;
$$;
